version: '3.11'

services:

  shop_web:
    build:
      context: .
      dockerfile: docker/shop/Dockerfile
    image: shop:0.0.1-dev
    container_name: shop_web
    command: sh /home/user/app/docker/runserver.sh
    env_file:
      - shop/.env
    expose:
      - 8000
    networks:
      - nginx_network
      - shop_db_net
      - shop_warehouse_network
#    volumes:
#      - ./shop:/home/user/app
#      - ./docker/shop/entrypoint.sh:/home/user/app/docker/entrypoint.sh
#      - ./docker/shop/runserver.sh:/home/user/app/docker/runserver.sh
    depends_on:
      - db_shop



  warehouse_web:
    build:
      context: .
      dockerfile: docker/warehouse/Dockerfile
    image: warehouse:0.0.1-dev
    container_name: warehouse_web
    command: sh /home/user/app/docker/runserver.sh
    env_file:
      - warehouse/.env
    expose:
      - 8001
    networks:
      - nginx_network
      - warehouse_db_net
      - shop_warehouse_network
#    volumes:
#      - ./warehouse:/home/user/app
#      - ./docker/warehouse/entrypoint.sh:/home/user/app/docker/entrypoint.sh
#      - ./docker/warehouse/runserver.sh:/home/user/app/docker/runserver.sh

    depends_on:
      - db_warehouse

  db_shop:
    container_name: db_shop
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=shop_db
      - POSTGRES_USER=shop_admin
      - POSTGRES_PASSWORD=shop_admin
    volumes:
      - shop-database-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - shop_db_net
      - web_network

  db_warehouse:
    container_name: db_warehouse
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=warehouse_db
      - POSTGRES_USER=warehouse_admin
      - POSTGRES_PASSWORD=warehouse_admin
    volumes:
      - warehouse-database-data:/var/lib/postgresql/data
    expose:
      - 5433
    networks:
      - warehouse_db_net
      - web_network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: on-failure
    networks:
      - nginx_network
    ports:
      - 80:80
      - 81:81
    depends_on:
      - shop_web
      - warehouse_web
    healthcheck:
      test: [ "CMD-SHELL", "ps ax", "|" ,"grep -v grep", "|" ,"grep nginx",  "||", "exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    networks:
     - nginx_network
     - web_network



networks:
  nginx_network:
  warehouse_db_net:
  shop_db_net:
  shop_warehouse_network:
  web_network:

volumes:
  shop-database-data:
  warehouse-database-data:
